apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsc-cloudflare-dns-pv-claim
  namespace: jsc-ns
  labels:
    app: jsc-cloudflare-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsc-cloudflare-dns
  namespace: jsc-ns
  labels:
    app: jsc-cloudflare-dns
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jsc-cloudflare-dns
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: jsc-cloudflare-dns
        tier: backend
    spec:
      containers:
        - image: jscdroiddev/jsc-cloudflare-dns:latest
          name: jsc-cloudflare-dns
          resources:
            requests:
              ephemeral-storage: "500Mi"
            limits:
              ephemeral-storage: "1Gi"
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: NODE_ENV
              value: production
            - name: STORAGE_PATH
              value: /data
            - name: CLOUDFLARE_URL
              valueFrom:
                secretKeyRef:
                  name: jcd-secret
                  key: cloudflare_url
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jcd-secret
                  key: cloudflare_api_key
          volumeMounts:
            - name: jsc-cloudflare-dns-persistent-storage
              mountPath: /data
      volumes:
        - name: jsc-cloudflare-dns-persistent-storage
          persistentVolumeClaim:
            claimName: jsc-cloudflare-dns-pv-claim
